apiVersion: v1
kind: Service
metadata:
  name: abnnpservice-srv
spec:
  type: NodePort
  selector:
    app: abnservice
  ports:
    - name: abnservice
      protocol: TCP
      port: 80
      targetPort: 80