apiVersion: apps/v1
kind: Deployment
metadata:
  name: abn-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abnservice
  template:
    metadata:
      labels:
        app: abnservice
    spec:
      containers:
        - name: abnservice
          image: andy2078/abnservice:latest